version: "3.8"
services:
  flaskapp:
    build:
        context: "."
        dockerfile: "Dockerfile"
    ports:
      - 80:5000
    depends_on: 
      - "postgres"
    restart: "on-failure" 
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=pswd
      - POSTGRES_USER=root
      - POSTGRES_DB=db_exam
    restart: "on-failure"
    